import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main()=>runApp(const StudioApp());
class StudioApp extends StatelessWidget{const StudioApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'AI YouTube Studio',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.deepPurple),home:const Home());}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{
 final topic=TextEditingController(); final base='http://10.0.2.2:8000';
 String mode='short',style='realistic_3d',aspect='9:16',privacy='private',msg='Ready'; Map<String,dynamic>? project; double progress=0;
 Future<void> createPlan() async{if(topic.text.trim().isEmpty)return;setState(()=>msg='Creating story...');final r=await http.post(Uri.parse('$base/api/project/plan'),headers:{'Content-Type':'application/json'},body:jsonEncode({'topic':topic.text,'mode':mode,'language':'hi','style':style}));if(r.statusCode==200)setState((){project=jsonDecode(r.body);msg='Story ready';});else setState(()=>msg='Error: ${r.body}');}
 Future<void> assets() async{if(project==null)return;setState(()=>msg='Generating images and Hindi voice...');final r=await http.post(Uri.parse('$base/api/project/${project!['project_id']}/assets'),headers:{'Content-Type':'application/json'},body:jsonEncode({'style':style,'aspect_ratio':aspect}));if(r.statusCode==200)setState((){project=jsonDecode(r.body);msg='Assets ready';});else setState(()=>msg='Error: ${r.body}');}
 Future<void> thumbnail() async{if(project==null)return;setState(()=>msg='Creating thumbnail...');final id=project!['project_id'];final r=await http.post(Uri.parse('$base/api/project/$id/thumbnail'),headers:{'Content-Type':'application/json'},body:jsonEncode({'project_id':id}));if(r.statusCode==200)setState(()=>msg='Thumbnail ready');else setState(()=>msg='Thumbnail error: ${r.body}');}
 Future<void> render() async{if(project==null)return;setState(()=>msg='Rendering...');final r=await http.post(Uri.parse('$base/api/render'),headers:{'Content-Type':'application/json'},body:jsonEncode({'project_id':project!['project_id'],'aspect_ratio':aspect}));if(r.statusCode!=200){setState(()=>msg='Render error: ${r.body}');return;}final jid=jsonDecode(r.body)['job_id'];final timer=Timer.periodic(const Duration(seconds:1),(t)async{final x=await http.get(Uri.parse('$base/api/jobs/$jid'));if(x.statusCode!=200)return;final j=jsonDecode(x.body);if(mounted)setState(()=>progress=((j['progress']??0) as num)/100);if(j['status']=='done'){t.cancel();if(mounted)setState(()=>msg='Video ready');}if(j['status']=='error'){t.cancel();if(mounted)setState(()=>msg='Render failed: ${j['message']}');}});}
 Future<void> pipeline() async{if(project==null)return;setState(()=>msg='Running full AI production...');final id=project!['project_id'];final r=await http.post(Uri.parse('$base/api/pipeline'),headers:{'Content-Type':'application/json'},body:jsonEncode({'project_id':id,'aspect_ratio':aspect,'make_thumbnail':true}));if(r.statusCode!=200){setState(()=>msg='Pipeline error: ${r.body}');return;}final jid=jsonDecode(r.body)['job_id'];final timer=Timer.periodic(const Duration(seconds:1),(t)async{final x=await http.get(Uri.parse('$base/api/jobs/$jid'));if(x.statusCode!=200)return;final j=jsonDecode(x.body);if(mounted)setState(()=>progress=((j['progress']??0) as num)/100);if(j['status']=='done'){t.cancel();final pr=await http.get(Uri.parse('$base/api/project/$id'));if(pr.statusCode==200&&mounted)setState(()=>project=jsonDecode(pr.body));if(mounted)setState(()=>msg='Full video package ready');}if(j['status']=='error'){t.cancel();if(mounted)setState(()=>msg='Pipeline failed: ${j['message']}');}});}
Future<void> saveMetadata() async{if(project==null)return;final id=project!['project_id'];final r=await http.patch(Uri.parse('$base/api/project/$id/metadata'),headers:{'Content-Type':'application/json'},body:jsonEncode({'title':project!['title'],'description':project!['description'],'tags':project!['tags']}));if(mounted)setState(()=>msg=r.statusCode==200?'Metadata saved':'Metadata save error');}
Future<void> upload() async{if(project==null)return;setState(()=>msg='Uploading to YouTube...');final r=await http.post(Uri.parse('$base/api/youtube/upload'),headers:{'Content-Type':'application/json'},body:jsonEncode({'project_id':project!['project_id'],'privacy':privacy,'category_id':'22','upload_captions':true}));if(mounted)setState(()=>msg=r.statusCode==200?'YouTube upload complete':'YouTube upload error: ${r.body}');}
 @override Widget build(BuildContext c){final scenes=(project?['scenes']??[]) as List;return Scaffold(appBar:AppBar(title:const Text('AI YouTube Studio — Phase 9')),body:ListView(padding:const EdgeInsets.all(16),children:[
  TextField(controller:topic,decoration:const InputDecoration(labelText:'Story / Topic',border:OutlineInputBorder())),const SizedBox(height:12),
  DropdownButtonFormField(value:mode,decoration:const InputDecoration(labelText:'Video type'),items:const[DropdownMenuItem(value:'short',child:Text('YouTube Short')),DropdownMenuItem(value:'long',child:Text('Long Video'))],onChanged:(v)=>setState(()=>mode=v!)),const SizedBox(height:12),
  DropdownButtonFormField(value:aspect,decoration:const InputDecoration(labelText:'Aspect ratio'),items:const[DropdownMenuItem(value:'9:16',child:Text('9:16 — Shorts')),DropdownMenuItem(value:'16:9',child:Text('16:9 — YouTube'))],onChanged:(v)=>setState(()=>aspect=v!)),const SizedBox(height:12),
  DropdownButtonFormField(value:privacy,decoration:const InputDecoration(labelText:'YouTube privacy'),items:const[DropdownMenuItem(value:'private',child:Text('Private')),DropdownMenuItem(value:'unlisted',child:Text('Unlisted')),DropdownMenuItem(value:'public',child:Text('Public'))],onChanged:(v)=>setState(()=>privacy=v!)),const SizedBox(height:12),
  FilledButton(onPressed:createPlan,child:const Text('1. Create AI Story')),FilledButton(onPressed:assets,child:const Text('2. Generate Images + Hindi Voice')),FilledButton(onPressed:thumbnail,child:const Text('3. Create AI Thumbnail')),FilledButton(onPressed:render,child:const Text('4. Render Final Video')),FilledButton(onPressed:pipeline,child:const Text('⚡ One-Click: Create Complete Video')),FilledButton(onPressed:saveMetadata,child:const Text('Save YouTube Metadata')),FilledButton(onPressed:upload,child:const Text('6. Upload to YouTube')),
  const SizedBox(height:8),LinearProgressIndicator(value:progress),Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Text(msg)),
  if(project!=null)...[Text(project!['title']??'',style:Theme.of(c).textTheme.titleLarge),...scenes.map((s)=>Card(child:ListTile(leading:CircleAvatar(child:Text('${s['scene']}')),title:Text('Scene ${s['scene']}'),subtitle:Text(s['narration']??'',maxLines:3,overflow:TextOverflow.ellipsis))))]
 ]));}
}
